### ISSUE TITLE
Not installing on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by snowmountain77** [vitaly-zdanevich/geeknote#7]
I've tried everything.

Is there just a deb file or pip install or something?

**Comment by vitaly-zdanevich** [comment]
I have no Ubuntu of this version to test. Try

```
python setup.py build
pip install --upgrade .
```

**Comment by snowmountain77** [comment]
I did the first part and got this: 

> Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    keywords="Evernote, console",
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 895, in install_eggs
    os.path.abspath(dist_filename)
distutils.errors.DistutilsError: Couldn't find a setup script in /tmp/easy_install-DReZ_A/pytest-runner-6.0.1.tar.gz

**Comment by snowmountain77** [comment]
The second part got this: 

> Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Du2bpm-build/setup.py", line 108, in <module>
        keywords="Evernote, console",
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 895, in install_eggs
        os.path.abspath(dist_filename)
    distutils.errors.DistutilsError: Couldn't find a setup script in /tmp/easy_install-yMGRS6/pytest-runner-6.0.1.tar.gz
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Du2bpm-build/

**Comment by vitaly-zdanevich** [comment]
`/usr/lib/python2.7`

Python2 is dead, this repo is for Python3. But if you want Python2 - maybe this still works https://github.com/jeffkowalski/geeknote/tree/2.0.22
